language: node_js
node_js:
- '4'
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: TpxjrK2ahT2xYU/oSMmYsqGwl9zicxFDAAT2cwiU/vFdoLr6yI3ZifW7UTYxlwemccMIVrs3EMbNHoGqbCtEr/oOK3fl42WWFJl9hmTk8+TlYLHMtGoTjvVw2MaOq8FAQaEaejVBu2iNnFZZo9sWJ9mBdRYYsXxcSwC0Zf6EhiGVWwZyCs+X/u7pccMOA2J7/AkcFqSqtgzsga4Ehfcz9nTgqQgGf385waYRjgEsDY3PehLPht7HOYcm2pHkRDKwgMaOhnO5CuPFem+jvdPLA2ueFbdtVd5Zh0atm0iq68TSammgTX46twZzsm1v11daqvVXZ2fcB6JCk742fxzKfiSPKjfa1JgfAz+jO7J3M84G6HtlOn6DEH+uPWZir5kiP33GRgU3JmT3yKXyqh0Rrg1K+g4tyi1XxNE6ZlnRL6bXSFTUMi7ZfaBZ2oNCFoX5O96NWDTakNuOi9GntU7MFGBm5CEpk7b1NAj+ppQvyNVvuzavHCPmJPWYGbF6+oscyKx/qIDlrBE684zRoAHJvcw/rxhHGngFYoIqDOiFmz8nhjQo3AeCUzGH9xNx9/sucEgXB013DPWlq3HS0ltxQHumfzIoJXEgQcunXlAIXndbON2f2L0W5NUakYd/o5lHdc26EHWzoRW5+P68PjDl5uZblgJHdnwN+WP4+yBKvk4=
